// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKSfauPZwxrQoH_KP9gQBgThP5LlrAxvs',
    appId: '1:1036408704740:android:d74a7c6e08482dc2e6e6f1',
    messagingSenderId: '1036408704740',
    projectId: 'proyecto-jardinerito',
    databaseURL: 'https://proyecto-jardinerito-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-jardinerito.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUk83kGOaXja-WjxKz1poM3mbw41AZaaI',
    appId: '1:1036408704740:ios:a41a48eb4a8503cfe6e6f1',
    messagingSenderId: '1036408704740',
    projectId: 'proyecto-jardinerito',
    databaseURL: 'https://proyecto-jardinerito-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-jardinerito.firebasestorage.app',
    iosBundleId: 'com.example.appjardinerito',
  );
}
